// Components
import Head from 'next/head'
import Header from '../components/header/Header'
import Board from '../components/board/Board'
import Footer from '../components/footer/Footer'

// CSS
import styles from '../styles/Home.module.css'

// Fonts
import { Roboto } from '@next/font/google'

const roboto = Roboto({ subsets: ['latin'], weight: ['400','500','700'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>React + TS Sudoku Solver</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header></Header>
      <main className={`${roboto.className} ${styles.main}`}>
        <Board></Board>
      </main>
      <Footer></Footer>
    </>
  )
}
